### ISSUE TITLE
Error: CURLcode=35

### ISSUE THREAD

**Issue by firedevel** [1Conan/tsschecker#15]
## CURL Version
curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1n zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

## Logs
tsschecker version: 0.378-39daf4d4267ec867cccc4ccdcedaa0f9115011b8
libfragmentzip version: 0.Debug-Build: Feb 10 2022 01:29:39-RELEASE
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "***" to dec:*** hex:***
[TSSC] opening firmwares.json
[JSON] counting elements
[JSON] parsing elements
[WARNING] [TSSC] error parsing cached firmware.json. Trying to redownload
[TSSC] opening firmwares.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[Error] failed to download file from=https://api.ipsw.me/v2.1/firmwares.json/condensed to=/tmp/firmwares.json CURLcode=35
[JSON] counting elements
[JSON] parsing elements
[Error] [TSSC] parsing firmware.json failed

**Comment by firedevel** [comment]
i tried ` curl https://api.ipsw.me/v2.1/firmwares.json/condensed >> /tmp/firmwares.json` and it still not work:

tsschecker version: 0.378-39daf4d4267ec867cccc4ccdcedaa0f9115011b8
libfragmentzip version: 0.Debug-Build: Feb 10 2022 01:29:39-RELEASE
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed * to dec:* hex:*
[TSSC] opening firmwares.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] selecting latest version of firmware: 16.1.1
[TSSC] got firmwareurl for iOS 16.1.1 build 20B101
[TSSC] opening Buildmanifest for iPhone10,1_16.1.1_20B101
[Error] [TSSR] Error: could not get BuildIdentities
[WARNING] [TSSC] could not get BuildIdentity for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[Error] [TSSR] Error: could not get BuildIdentities
[Error] [TSSR] Error: could not get BuildIdentity for installType=Update
[Error] [TSSR] failed to build tss request

[Error] [TSSC] checking tss status failed!

**Comment by Cryptiiiic** [comment]
378 is outdated, use build 413 @firedevel

**Comment by Cryptiiiic** [comment]
@firedevel don't create and issue then leave.
