### ISSUE TITLE
Error make 

### ISSUE THREAD

**Issue by salvatore8686** [1Conan/tsschecker#23]
Hi, can you help me solve this problem? MacBook M1  Pro. Thanks!

salvatoredebari@Computealvatore tsschecker % make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in tsschecker
gcc -DHAVE_CONFIG_H -I. -I..    -I/opt/homebrew/Cellar/libplist/2.2.0/include -I/opt/homebrew/Cellar/libzip/1.9.2/include -I/usr/local/include   -I/opt/homebrew/Cellar/libirecovery/1.0.0/include  -I../external/jssy/jssy/ -g -O2 -std=gnu11 -D TSSCHECKER_VERSION_COUNT=\"418\" -D TSSCHECKER_VERSION_SHA=\"20b1170b0a50cffd1f32c12a6f2d2b1ca4a49f2a\" -MT tsschecker-tsschecker.o -MD -MP -MF .deps/tsschecker-tsschecker.Tpo -c -o tsschecker-tsschecker.o `test -f 'tsschecker.c' || echo './'`tsschecker.c
In file included from tsschecker.c:20:
./tsschecker.h:19:10: fatal error: 'jssy.h' file not found
#include "jssy.h"
         ^~~~~~~~
1 error generated.
make[2]: *** [tsschecker-tsschecker.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by Cryptiiiic** [comment]
`git submodule update --init --recursive`

@salvatore8686 please learn how to clone git repos

**Comment by salvatore8686** [comment]
> `git submodule update --init --recursive`
> 
> @salvatore8686per favore impara come clonare i repository git
I had cloned with --recursive, thanks a lot!
