### ISSUE TITLE
iOS 16, new device support, bugs, etc (stuff to do)

### ISSUE THREAD

**Issue by DanTheMann15** [1Conan/tsschecker#8]
* tsscecker is unable to request noNonce aptickets. (broken since 9a04650, i believe i fixed it in 6044c9c)
* Support the latest devices.
* Add the bbgcid's for the Mav30 and Mav22 chips. (they are below)
* Fix iPhone 14 Pro blob checking, (patched in eda8e95 and further mitigated with 78f4523).
* Fix `--print-tss-request` and `--print-tss-response`. (broken since 9a04650, fixed in 4e64ef0)

Baseband Cert ID's
Mav30: `2241363181, 4` iPhone SE (3rd generation)
Mav22: `3559316616, 4` iPhone 14 Family

you guys might also want to check out what i've done in my fork and implementing some of this stuff here.
https://github.com/DanTheMann15/tsschecker

**Comment by Cryptiiiic** [comment]
@DanTheMann15 try 87b9717, I'll reopen if this is still missing stuff

**Comment by DanTheMann15** [comment]
@Cryptiiiic i'll check it out. thanks!
